[package]
name = "solarhorizon/rodux-utils"
description = "A collection of utilities for use with Rodux"
authors = ["SolarHorizon"]
version = "0.4.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]

[dependencies]
Immut = "solarhorizon/immut@0.4.3"
